CREATE DATABASE IF NOT EXISTS `dobby`;

USE dobby;

DROP TABLE IF EXISTS companies;

create table `companies` (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    search_id VARCHAR(255) NOT NULL,
    market_price DECIMAL(12, 2),
    p_e_ratio DECIMAL(5, 2),
    market_cap DECIMAL(12, 2),
    divident_yield_percentage DECIMAL(5, 2),
    quaterly_sales_in_crores DECIMAL(12, 2),
    quaterly_sales_growth_percentage DECIMAL(5, 2),
    return_on_capital_employed_percentage DECIMAL(6, 2),
    tag VARCHAR(255) NOT NULL
);
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('HDFC Bank','hdfc-bank-ltd',1636.9,18.72,1239557.41,1.16,51168.14,37.28,6.24,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('ICICI Bank','icici-bank-ltd',990.5,18.6,693376.03,0.81,37105.89,41.85,6.35,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('State Bank of India','state-bank-of-india',588.35,7.86,525212.69,1.92,101460.01,32.14,5.21,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Kotak Mahindra Bank','kotak-mahindra-bank-ltd',1811.2,22.06,359987.05,0.08,12868.93,40.42,6.86,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Axis Bank','axis-bank-ltd',1000.9,13.51,308447.72,0.1,26245.74,36.74,6.16,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('IndusInd Bank','indusind-bank-ltd',1429.15,14.03,110979.5,0.98,10729.65,31.14,7.37,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Bank of Baroda','bank-of-baroda',199.95,5.94,103375.89,2.75,28002.54,39.68,5.17,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Punjab National Bank','punjab-national-bank',66.85,16.69,73566.08,0.97,25672.85,34.11,4.11,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('IDBI Bank','idbi-bank-ltd',65.7,16.96,70673.5,1.52,6863.63,47.97,4.26,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Union Bank of India','union-bank-of-india',87.6,6.37,64925.81,3.42,23613.18,29.35,5.02,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Canara Bank','canara-bank',348.8,4.94,63259.29,3.44,25450.79,37.3,5.33,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('IDFC First Bank','idfc-bank-ltd',93.45,22.79,62254.63,0.0,6868.86,39.56,6.59,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Indian Overseas Bank','indian-overseas-bank',32.35,27.69,61114.23,0.0,5424.31,22.31,4.53,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Yes Bank','yes-bank-ltd',17.55,65.72,50495.64,0.0,6445.36,25.52,4.94,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('AU Small Finance Bank','au-small-finance-bank-ltd',718.45,31.03,48005.52,0.14,2458.34,35.06,7.39,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Indian Bank','indian-bank',383.8,7.83,47824.09,2.24,13049.94,28.37,4.55,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Union Bank of India','union-bank-of-india',98.45,8.52,40379.17,2.03,14442.14,43.8,4.42,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('UCO Bank','uco-bank',33.65,20.5,40231.8,0.0,5223.92,35.65,4.75,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Bandhan Bank','bandhan-bank-ltd',232.85,18.49,37516.7,0.64,4522.91,11.53,6.67,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Federal Bank','the-federal-bank-ltd',142.6,9.83,33511.03,0.7,5349.77,39.2,5.91,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Central Bank of India','central-bank-of-india',37.6,17.15,32608.25,0.0,7258.97,30.67,4.29,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Bank of Maharashtra','bank-of-maharashtra',41.1,9.12,27674.84,3.16,4788.66,38.5,4.44,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Punjab & Sind Bank','punjab-sind-bank',38.55,20.71,26109.68,1.25,2315.79,28.62,5.26,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('RBL Bank','rbl-bank-ltd',217.8,13.5,13089.99,0.69,2679.85,28.26,5.46,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Karur Vysya Bank','karur-vysya-bank-ltd',129.9,8.44,10429.67,1.54,1882.91,27.78,5.95,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('City Union Bank','city-union-bank-ltd',130.25,10.27,9651.04,0.77,1266.17,15.16,5.62,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Ujjivan Small Finance Bank','ujjivan-small-finance-bank-ltd',48.45,7.76,9474.11,2.58,1286.88,42.14,10.63,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Equitas Small Finance Bank','equitas-small-finance-bank-ltd',83.85,14.02,9363.26,1.19,1253.96,33.34,8.04,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Jammu & Kashmir Bank','the-jammu-kashmir-bank-ltd',96.15,6.84,9244.63,0.52,2657.21,26.34,4.92,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Tamilnad Mercantile Bank','tamilnad-mercantile-bank-ltd',573.95,8.6,9088.58,0.87,1155.89,15.34,6.41,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Karnataka Bank','the-karnataka-bank-ltd',226.0,4.92,7067.97,2.21,1958.74,20.24,5.86,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('CSB Bank','csb-bank-ltd',324.0,9.96,5625.97,0.0,683.49,27.53,6.45,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Utkarsh Small Finance Bank','utkarsh-small-finance-bank-ltd',47.6,12.9,5217.59,0.0,720.5,26.22,9.37,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('South Indian Bank','the-south-indian-bank-ltd',22.85,5.55,4781.91,1.31,2025.04,24.86,5.23,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('DCB Bank','dcb-bank-ltd',116.9,7.36,3647.84,1.07,1237.74,30.39,6.71,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Fino Payments Bank','fino-payments-bank-ltd',344.75,39.0,2873.33,0.0,32.97,76.03,7.17,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Suryoday Small Finance Bank','suryoday-small-finance-bank-ltd',155.2,14.02,1647.61,0.0,358.09,27.23,9.3,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dhanlaxmi Bank','dhanlaxmi-bank-ltd',22.9,5.55,578.22,0.0,289.14,11.91,4.66,'Banking');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Apollo Hospitals Enterprise','apollo-hospitals-enterprise-ltd',4979.2,107.11,71610.12,0.3,4417.8,16.39,14.94,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Max Healthcare Institute','max-healthcare-institute-ltd',618.45,51.43,60213.56,0.16,1284.99,20.44,14.99,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Fortis Healthcare','fortis-healthcare-ltd',335.3,48.5,25332.3,0.3,1657.41,11.4,10.89,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Narayana Hrudayalaya','narayana-hrudayalaya-ltd',1039.8,31.25,21241.17,0.24,1233.43,19.35,31.6,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dr Lal PathLabs','dr-lal-pathlabs-ltd',2205.85,69.85,18426.3,0.54,541.0,7.62,18.47,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Global Health','global-health-ltd',676.7,49.17,18161.25,0.0,773.04,25.2,17.09,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Aster DM Healthcare','aster-dm-healthcare-ltd',338.5,46.78,16900.97,0.0,3215.37,20.78,9.67,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Krishna Institute of Medical Sciences','krishna-institute-of-medical-sciences-ltd',2065.6,49.01,16508.54,0.0,606.03,22.3,25.43,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Poly Medicure','poly-medicure-ltd',1339.5,59.7,12836.17,0.22,320.83,28.93,18.34,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Rainbow Children's Medicare','rainbow-childrens-medicare-ltd',1019.15,48.41,10343.54,0.29,287.17,21.09,24.17,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Metropolis Healthcare','metropolis-healthcare-ltd',1398.35,51.83,7168.26,0.57,277.09,-0.99,17.41,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Global Health','global-health-ltd',365.4,270.65,5085.61,0.0,460.68,12.9,8.44,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Vijaya Diagnostic Centre','vijaya-diagnostic-centre-ltd',474.25,51.98,4854.04,0.21,121.05,15.99,18.49,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Yatharth Hospital & Trauma Care Services','yatharth-hospital-trauma-care-services-ltd',355.35,46.35,3048.26,0.0,154.51,39.11,26.58,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Thyrocare Technologies','thyrocare-technologies-ltd',549.15,52.28,2906.14,3.28,123.61,3.66,15.28,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Kovai Medical Center & Hospital','kovai-medical-center-hospital-ltd',2588.1,23.03,2833.96,0.19,274.61,16.34,16.79,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Shalby','shalby-ltd',236.6,37.29,2550.55,0.51,235.49,16.76,10.55,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Krsnaa Diagnostics','krsnaa-diagnostics-ltd-643',635.55,32.28,1998.14,0.43,132.29,18.36,11.94,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Artemis Medicare Services','artemis-medicare-services-ltd',129.05,42.91,1756.47,0.35,201.19,23.07,11.45,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Indraprastha Medical Corporation','indraprastha-medical-corporation-ltd',159.85,15.31,1474.99,1.88,306.51,16.4,34.33,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('KMC Speciality Hospitals (India)','kmc-speciality-hospitals-india-ltd',84.81,50.26,1383.26,0.0,40.84,16.52,26.67,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dr Agarwal's Eye Hospital','dr-agarwals-eye-hospital-ltd',2297.2,27.44,1079.69,0.13,77.8,17.19,18.6,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Vasa Denticity','vasa-denticity-ltd',450.0,94.83,720.73,0.0,0.0,0.0,111.65,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Prevest Denpro','prevest-denpro-ltd',454.8,33.89,545.89,0.22,13.39,8.25,32.25,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Asarfi Hospital','asarfi-hospital-ltd',122.75,30.12,241.54,0.0,0.0,0.0,26.21,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Hemant Surgical Industries','hemant-surgical-industries-ltd',220.05,29.95,229.74,0.0,0.0,0.0,45.03,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Lotus Eye Hospital & Institute','lotus-eye-hospital-and-institute-ltd',88.1,43.9,179.55,0.57,12.57,5.9,10.25,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Aashka Hospitals','aashka-hospitals-ltd',58.09,0.0,135.93,0.0,7.41,0.0,0.42,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Fortis Malar Hospitals','fortis-malar-hospitals-ltd',59.4,0.0,111.33,0.0,17.76,-11.64,-0.77,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Aatmaj Healthcare','aatmaj-healthcare-ltd',48.45,18.53,109.49,0.0,0.0,0.0,69.0,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Shree Pacetronix','shree-pacetronix-ltd',295.9,28.63,106.51,0.0,5.86,74.93,46.15,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Jeevan Scientific Technology','jeevan-scientific-technology-ltd',60.44,0.0,93.56,1.99,10.39,0.58,-4.42,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Tejnaksh Healthcare','tejnaksh-healthcare-ltd',33.45,52.27,67.95,0.0,3.03,5.21,11.37,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Deccan Health Care','deccan-health-care-ltd',35.97,153.26,61.31,0.0,11.22,28.38,0.82,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Nidan Laboratories And Healthcare','nidan-laboratories-and-healthcare-ltd',36.55,15.21,50.8,0.0,10.18,0.0,8.17,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('NG Industries','ng-industries-ltd',148.65,5.25,49.8,2.35,4.53,-18.23,6.58,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Global Longlife Hospital and Research','global-longlife-hospital-and-research-ltd',47.24,27.11,49.61,0.0,11.7,0.0,6.35,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('One Global Service Provider','overseas-synthetics-ltd',61.0,19.51,43.31,0.0,12.52,499.04,19.74,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Family Care Hospitals','scandent-imaging-ltd',7.86,8.03,42.46,0.64,11.93,6.14,23.05,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Aspira Pathlab & Diagnostics','aspira-pathlab-diagnostics-ltd',35.37,0.0,36.41,0.0,2.6,-12.46,2.01,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Bandaram Pharma Packtech','shiva-medicare-ltd',27.84,59.66,33.41,0.0,5.87,545.05,6.17,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Transgene Biotek','transgene-biotek-ltd',4.36,0.0,33.04,0.0,0.1,66.67,-21.64,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Adeshwar Meditex','adeshwar-meditex-ltd',22.5,15.69,32.47,0.0,36.3,0.0,9.99,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Centenial Surgical Suture','centenial-surgical-suture-ltd',78.51,28.37,28.65,0.0,13.66,1.26,8.03,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Medinova Diagnostic Services','medinova-diagnostic-services-ltd',28.4,16.77,28.35,0.0,2.42,-1.63,2684.21,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Gian Life Care','gian-life-care-ltd',25.39,14.75,26.26,0.0,2.43,-1.62,12.29,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Chennai Meenakshi Multispeciality Hospital','chennai-meenakshi-multispeciality-hospital-ltd',27.71,23.52,20.7,0.0,6.55,2.83,21.36,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dr Lalchandani Labs','dr-lalchandani-labs-ltd',27.6,0.0,11.96,0.0,2.76,0.0,-3.65,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Soni Medicare','soni-medicare-ltd',26.79,0.0,11.43,0.0,7.54,12.87,0.81,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Looks Health Services','looks-health-services-ltd',6.18,0.0,6.49,0.0,0.0,-100.0,-0.67,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Transpact Enterprises','transpact-enterprises-ltd',150.75,0.0,5.83,0.0,0.0,0.0,-7.87,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dhanvantri Jeevan Rekha','dhanvantri-jeevan-rekha-ltd',13.0,0.0,5.33,0.0,4.98,21.46,-1.38,'Healthcare');
insert into `companies` (company_name,search_id,market_price,p_e_ratio,market_cap,divident_yield_percentage,quaterly_sales_in_crores,quaterly_sales_growth_percentage,return_on_capital_employed_percentage,tag) values ('Dolphin Medical Services','dolphin-medical-services-ltd',1.85,0.0,2.79,0.0,0.15,0.0,-0.91,'Healthcare');